apiVersion: v1
kind: Service
metadata:
  name: stockpriceserver
  namespace: istio-demo
spec:
  selector:
    app: stockpricerserver
    type: pod
    version: v1
  ports:
  - port: 9002
    targetPort: 8092
