apiVersion: v1
kind: Service
metadata:
  name: clientserver
  namespace: istio-demo
  labels:
    type: service
    version: v1
spec:
  selector:
    app: clientserver
    type: pod
    version: v1
  ports:
  - port: 9000
    targetPort: 8090
