apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherserver
  namespace: istio-demo
  labels:
    type: deployment
    version: v1
spec:
  selector:
    matchLabels:
      app: weatherserver
      type: pod
      version: v1
  template:
    metadata:
      labels:
        app: weatherserver
        type: pod
        version: v1
    spec:
      containers:
      - name: weatherserver
        image: weatherserver:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8091
